travis:
  secure:
    BINSTAR_TOKEN: p2cz2h6qf8wBVE+VumPXihdEmsM78Lp+DM0fQQQR367tXgaOswDxtpD+bK9QVlsKX+hWjuPwHm+/CzDg4dzdToZMwT46te3DErfHFB2RAMLLvTDk9u1BJQgYZhyzID+qmSf5aKK7EHfCJvbnThLc46HAkW0gbRzkLz3EyLetAmlNELu4kgMl11N/iqwSDxrPo9GfIFf/5rTaXPfYJg2tXuQTIeijHWaU2krzGCQ2AoL8qIn7/nRN2pBMK8V6YJaLbKzbgC/oHPGpYMQlMvGgM+6EJic1NfQ7ipZERUJwhlXUlqO+znxz02lzzjTWKPNFTdPVsSJU72tEC+3n4JdlE5XQ0Wh/UdRMHan2WCUM5FIfq/HXw7AagNeP6G7hrtbzlnQuyjRVkIeYssDNQq7WzRkQhXP2heu9sNtas/Y/kgBXCfJ1NG9M0ODEekqo9FaJNPMw5MnP04jgydEqIXDFVGj8f+3lWQv1bpkMLidLJaU1w5yGri1c8oivtxi8+Qu8EARl3f40LOn+lNte9wsy0RKtxWfDLc04wcVRa4XaC/oKrdmq0SKb7Sk4yzVjJ78QfR8e81BqBnlnsWcn0mzN/U2cdgFYfsrjLRN8Ji3kumIO/Oy+fUkCU++/xNOPeEf/+XLyPmd+USyMoqwiLnbJ2IqssGOUxdPaaDSUJeWm5po=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
