travis:
  secure:
    BINSTAR_TOKEN: mFwXDnq9w5gNe0Qg0DzP3jPUVWsX+xzCWFXqfPAVJl2Dp7bQVrOthHXxrFGqJM/IHirfLcCxKoqAPD4B23JYV2hXk3E+Bly9sA53pVFUYb9fwBdyStjynmLLtu7UhLNm4L6HsJszb3CzBobUafwOicqg4p+4R8ti7A7tRgMsHFPaetcdJnUTmsEI/drdwUWytIVOEYTGrZIfUeTR0KIptRpWGTK42waJ+ZSVYdwL0uYPBiCpoWvySJq5C1693tnrqY8vjEihm+t5AGOw+hLHqzoHQB4ED5ss6QNd1T5h2ZMmm+GRpCKyBFNpoGbWANUnxmFsVU76k0KItE8gpXJK0LFZKq3l5Z3l9+3XSj9YDr7Wgq96OgcZ+vkKdYXyf/Ty16J3l0PpXGc4brOIlvrLhtx+hyIOGCvdq607GChNZP8kk7GGlrAMw1eeXA1x5xtd1pe+NTzZiUeSfRGC1438DBxI33Vpc+1byl2bjL3XuYTNqkDeWG3lyX7J88ritdU0thL53Awtm5SCMqcFEV4W6JYZk5iLDFN1MCWOmKsb80k8cKRBOC+xz8QhO/Okac8TOANA6YVzm3GIYeGTpmLI29pMyVHL7QnxEid6MLaY7o9OqYV+RQv6hy3Rf3p4izfX2PERKFPS2VuaX+I8QtfxSi6p1/LUAeS4zGpme4k5P70=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
